laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('quem-somos', 'QuemSomosController@index')->name('quem-somos');
    Route::get('como-funciona', 'ComoFuncionaController@index')->name('como-funciona');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contatoPost');
    Route::get('contrate', 'ContrateController@index')->name('contrate');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('banners', 'BannersController');
		Route::resource('vantagens', 'VantagensController');
		Route::resource('contrate', 'ContrateController', ['only' => ['index', 'update']]);
		// Route::resource('chamadas', 'ChamadasController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('quem-somos', 'QuemSomosController', ['only' => ['index', 'update']]);
		Route::resource('como-funciona', 'ComoFuncionaController', ['only' => ['index', 'update']]);
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Contato.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contato extends Model
{
    protected $table = 'contato';

    protected $guarded = ['id'];

    public function getWhatsappLinkAttribute()
    {
        $url      = 'https://api.whatsapp.com/send?phone=55';
        $whatsapp = str_replace(' ', '', $this->whatsapp);

        return $url.$whatsapp;
    }
}

laravel/resources/views/frontend/common/footer.blade.php
    <footer>
        <div class="center">
            <div class="links">
                <a href="{{ route('home') }}">_ HOME</a>
                <a href="{{ route('quem-somos') }}">_ QUEM SOMOS</a>
                <a href="{{ route('como-funciona') }}">_ COMO FUNCIONA</a>
                <a href="{{ route('contato') }}">_ CONTRATE JÁ</a>
            </div>

            <div class="contatos">
                <p class="telefone">
                    Fale conosco
                    <strong>{{ $contato->telefone }}</strong>
                </p>
                <a href="{{ $contato->whatsapp_link }}" class="whatsapp" target="_blank">
                    Fale pelo WhatsApp
                    <strong>{{ $contato->whatsapp }}</strong>
                </a>
            </div>

            <div class="social">
                @foreach(['facebook', 'instagram'] as $s)
                    @if($contato->{$s})
                    <a href="{{ $contato->{$s} }}" class="{{ $s }}" target="_blank">{{ $s }}</a>
                    @endif
                @endforeach
                <a href="mailto:?subject=Conheça a Riskin&body=www.riskin.com.br" class="compartilhar">compartilhar</a>
            </div>

            <img src="{{ asset('assets/img/layout/marca-riskin-rodape.png') }}" alt="{{ config('app.name') }}" class="marca">

            <div class="copyright">
                <p>
                    © {{ date('Y') }} {{ config('app.name') }}<br>
                    Todos os direitos reservados.
                </p>
                <p>
                    <a href="http://www.trupe.net" target="_blank">Criação de Sites</a>:<br>
                    <a href="http://www.trupe.net" target="_blank">Trupe Agência Criativa</a>
                </p>
            </div>
        </div>
    </footer>

laravel/resources/views/frontend/common/header.blade.php
    <header>
        <div class="center">
            <a href="{{ route('home') }}" class="logo">
                {{ config('app.name') }}
            </a>

            <nav>
                @include('frontend.common.nav')
            </nav>

            <div class="contatos">
                <p class="telefone">
                    Fale conosco
                    <strong>{{ $contato->telefone }}</strong>
                </p>
                <a href="{{ $contato->whatsapp_link }}" class="whatsapp" target="_blank">
                    Fale pelo WhatsApp
                    <strong>{{ $contato->whatsapp }}</strong>
                </a>
            </div>
        </div>
    </header>

laravel/resources/views/frontend/common/nav.blade.php
<a href="{{ route('home') }}" @if(Tools::routeIs('home')) class="active" @endif>
    HOME
</a>
<a href="{{ route('quem-somos') }}" @if(Tools::routeIs('quem-somos')) class="active" @endif>
    QUEM SOMOS
</a>
<a href="{{ route('como-funciona') }}" @if(Tools::routeIs('como-funciona')) class="active" @endif>
    COMO FUNCIONA
</a>
<a href="{{ route('contato') }}" @if(Tools::routeIs('contato')) class="active" @endif>
    CONTRATE JÁ
</a>

laravel/resources/views/frontend/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index, follow">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <meta name="author" content="Trupe Agência Criativa">
    <meta name="copyright" content="{{ date('Y') }} Trupe Agência Criativa">
    <meta name="description" content="{{ $config->description }}">
    <meta name="keywords" content="{{ $config->keywords }}">

    <meta property="og:title" content="{{ $config->title }}">
    <meta property="og:description" content="{{ $config->description }}">
    <meta property="og:site_name" content="{{ $config->title }}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ Request::url() }}">
@if($config->imagem_de_compartilhamento)
    <meta property="og:image" content="{{ asset('assets/img/'.$config->imagem_de_compartilhamento) }}">
@endif

    <title>{{ $config->title }}</title>

    <link rel="stylesheet" href="{{ asset('assets/css/vendor.main.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/main.css') }}">

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>
<body>
    @include('frontend.common.header')
    @yield('content')
    @include('frontend.common.footer')

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/typed.js/lib/typed.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-cycle2/build/jquery.cycle2.min.js') }}"></script>
    <script src="{{ asset('assets/js/main.js') }}"></script>

@if($config->analytics)
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', '{{ $config->analytics }}', 'auto');
        ga('send', 'pageview');
    </script>
@endif
</body>
</html>